[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
hwtr-disc = { path = "crates/hwtr-disc" }
hwtr-psx = { path = "crates/hwtr-psx" }
hwtr-data = { path = "crates/hwtr-data" }
hwtr-cpu = { path = "crates/hwtr-cpu" }
hwtr-game = { path = "crates/hwtr-game" }
hwtr-input = { path = "crates/hwtr-input" }
hwtr-hle = { path = "crates/hwtr-hle" }
hwtr-render = { path = "crates/hwtr-render" }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
