//! The reference docs, as a folder.
//!
//! `docs/README.md` is generated from the front matter of every page under
//! `docs/`, so the index cannot drift from the pages.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

const STATUS: [&str; 3] = ["solid", "partial", "guess"];
const DISCS: [&str; 3] = ["US", "EU", "all"];

const SECTIONS: [(&str, &str, &str); 5] = [
    ("disc", "The disc", "Tracks, the file system, boot, and what sits where on the CD."),
    ("formats", "File formats", "The containers and record layouts."),
    ("engine", "Engine", "How the game works, subsystem by subsystem."),
    ("content", "Content", "What is actually on the disc."),
    (
        "cut",
        "Cut and missing content",
        "Content the game names, references or half-carries but does not ship whole, one page per item.",
    ),
];

const HEADER: &str = "# Hot Wheels Turbo Racing reference

What is true about Hot Wheels Turbo Racing for the PlayStation (Stainless
Games / Electronic Arts, 1999, SLUS-00964), written for someone who wants to
write a parser or a subsystem. Generated by `hwtr-re docs index` - edit the
pages, not this file.

The [worklog](../WORKLOG.md) is the other half: it says how each of these was
worked out. `status` below is the honesty knob - `solid` means every field is
accounted for, `partial` means named unknowns remain, `guess` means a hypothesis
nobody has knocked down yet. `discs` says which releases the page has been
checked against: `US`, `EU`, or `all`.
";

const EMPTY: &str = "
No pages yet. The first format decoded gets the first page - see the `docs`
skill for the layout.
";

fn front_matter(path: &Path) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    let Ok(text) = std::fs::read_to_string(path) else { return out };
    let Some(body) = text.strip_prefix("---\n") else { return out };
    let Some(end) = body.find("\n---\n") else { return out };
    for line in body[..end].lines() {
        if let Some((key, value)) = line.split_once(':') {
            out.insert(key.trim().to_string(), value.trim().to_string());
        }
    }
    out
}

fn pages(docs: &Path, section: &str) -> Vec<(PathBuf, BTreeMap<String, String>)> {
    let mut found: Vec<PathBuf> = std::fs::read_dir(docs.join(section))
        .into_iter()
        .flatten()
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "md"))
        .collect();
    found.sort();
    found.into_iter().map(|p| (p.clone(), front_matter(&p))).collect()
}

fn cell(text: &str) -> String {
    text.replace('|', "\\|")
}

fn render_index(docs: &Path) -> String {
    let mut out = String::from(HEADER);
    let mut total = 0;
    for (section, heading, blurb) in SECTIONS {
        let found = pages(docs, section);
        if found.is_empty() {
            continue;
        }
        total += found.len();
        out.push_str(&format!("\n## {heading}\n\n{blurb}\n"));
        out.push_str("\n| Page | Status | Discs | Covers |\n| --- | --- | --- | --- |\n");
        for (path, meta) in found {
            let name = path.file_name().unwrap().to_string_lossy();
            let stem = path.file_stem().unwrap().to_string_lossy();
            let get = |k: &str, d: &str| meta.get(k).cloned().unwrap_or_else(|| d.to_string());
            out.push_str(&format!(
                "| [{}]({section}/{name}) | {} | {} | {} |\n",
                cell(&get("title", &stem)),
                get("status", "?"),
                cell(&get("discs", "?")),
                cell(&get("covers", "")),
            ));
        }
    }
    if total == 0 {
        out.push_str(EMPTY);
    }
    out
}

/// Relative `.md` link targets in a page: `](foo.md)` and `](../x/foo.md#a)`.
fn md_links(text: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut rest = text;
    while let Some(at) = rest.find("](") {
        rest = &rest[at + 2..];
        let end = rest.find(')').unwrap_or(rest.len());
        let target = &rest[..end];
        let target = target.split('#').next().unwrap_or("");
        if target.ends_with(".md") && !target.contains(':') {
            out.push(target);
        }
    }
    out
}

pub fn run(root: &Path, args: &[String]) -> Result<(), String> {
    let docs = root.join("docs");
    let index = docs.join("README.md");
    match args.first().map(String::as_str) {
        Some("index") => {
            std::fs::write(&index, render_index(&docs)).map_err(|e| e.to_string())?;
            let total: usize = SECTIONS.iter().map(|(s, _, _)| pages(&docs, s).len()).sum();
            println!("{total} pages -> docs/README.md");
            Ok(())
        }
        Some("check") => {
            let mut problems = Vec::new();
            for entry in std::fs::read_dir(&docs).map_err(|e| e.to_string())?.flatten() {
                let name = entry.file_name().to_string_lossy().to_string();
                if entry.path().is_dir() && !SECTIONS.iter().any(|(s, _, _)| *s == name) {
                    problems.push(format!(
                        "docs/{name}/ is not a section in crates/hwtr-re/src/docs.rs - its pages never reach the index"
                    ));
                }
            }
            for (section, _, _) in SECTIONS {
                for (path, meta) in pages(&docs, section) {
                    let at = path.strip_prefix(root).unwrap_or(&path).display().to_string();
                    for wanted in ["title", "status", "discs", "covers"] {
                        if meta.get(wanted).is_none_or(|v| v.is_empty()) {
                            problems.push(format!("{at} has no {wanted}"));
                        }
                    }
                    if let Some(status) = meta.get("status").filter(|s| !s.is_empty())
                        && !STATUS.contains(&status.as_str())
                    {
                        problems.push(format!("{at}: unknown status {status:?}; one of {}", STATUS.join(", ")));
                    }
                    for tag in meta.get("discs").map(String::as_str).unwrap_or("").split(',').map(str::trim) {
                        if !tag.is_empty() && !DISCS.contains(&tag) {
                            problems.push(format!("{at}: unknown disc {tag:?}; one of {}", DISCS.join(", ")));
                        }
                    }
                    // A dead cross-link in a reference page sends the reader
                    // looking for a page that was renamed or never written.
                    let text = std::fs::read_to_string(&path).unwrap_or_default();
                    for target in md_links(&text) {
                        if !path.parent().unwrap().join(target).exists() {
                            problems.push(format!("{at}: dead link to {target}"));
                        }
                    }
                }
            }
            if std::fs::read_to_string(&index).ok().as_deref() != Some(render_index(&docs).as_str()) {
                problems.push("docs/README.md is stale - run `hwtr-re docs index`".into());
            }
            for p in &problems {
                eprintln!("{p}");
            }
            if problems.is_empty() { Ok(()) } else { Err(format!("{} problems", problems.len())) }
        }
        _ => Err("usage: hwtr-re docs index|check".into()),
    }
}
